name: Production Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Copy env
        run: cp .env.example .env

      - uses: ./.github/actions/node-install

      - uses: ./.github/actions/cache-build
