name: Publish Docker

on:
  push:
    branches: ['release']

jobs:
  build:
    runs-on: warp-ubuntu-latest-arm64-16x

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push the docker image
        run: ./docker/buildx-and-push.sh
        env:
          PLATFORM: 'linux/amd64,linux/arm64'
